### ISSUE TITLE
is this against Mojang's TOS?

### ISSUE THREAD

**Issue by ghost** [abcd1234-byte/mc_1.18_src#1]
You are distributing the source code of the Minecraft client. I am not a legal expert, but this seems against their TOS.

**Comment by ghost** [comment]
It is in the src/main/java/ folder.

**Comment by jacobo-mc** [comment]
It is no more legal than the [mc_dev](https://github.com/Bukkit/mc-dev) repository or [Craftbukkit for beta 1.7.3](https://github.com/RhysB/Project-Poseidon). The takedown of Craftbukkit was because of a disgruntled contributer, not because mojang objected it.
